### ISSUE TITLE
Add support for cjs files

### ISSUE THREAD

**Issue by arthurfiorette** [beenotung/live-tsc#1]
Hello @beenotung, and hats off for making this package!

Currently, you are using esbuild to transpile the code and it does not fully respects tsconfig. My transpiled code keeps at ESM, while when running tsc it changes to CJS.

Can you add an `--cjs` option so that it can work for both modules?

After some research, you just need to add `format: 'cjs'` here.

https://github.com/beenotung/live-tsc/blob/1dc58b09a4e27bec04e0349d64a30c7f75d6f61d/src/core.ts#L399-L404

**Comment by beenotung** [comment]
Thanks for the suggestion, will make it when I get back to a computer soon

**Comment by beenotung** [comment]
It is published in v1.3.0 :tada:
